"""
run_synth.py -- open-source FPGA implementation of the RTL: Yosys synthesis
+ nextpnr place & route on two FPGA families, then a resource / Fmax report.

    python3 run_synth.py            # writes build/ and ../docs/synth_report.md
    python3 run_synth.py --check    # also fail if any target misses its clock

Targets (IO pins are left unconstrained -- the APB side of the wrapper would
connect to an on-chip CPU, not to package pins -- so the numbers are logic
resource / internal timing estimates):
  * Lattice iCE40 HX8K  (CT256)    -- e.g. iCE40-HX8K breakout board
  * Lattice ECP5 LFE5U-25F (CABGA256) -- e.g. ULX3S / OrangeCrab / Colorlight
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD = os.path.join(HERE, "build")
RTL = ["../rtl/spi_master.sv", "../rtl/spi_apb_wrapper.sv"]
TOPS = ["spi_master", "spi_apb_wrapper"]
TARGET_MHZ = 100

FAMILIES = {
    "iCE40 HX8K": dict(
        synth="synth_ice40", pnr=["nextpnr-ice40", "--hx8k", "--package", "ct256",
                                  "--pcf-allow-unconstrained"],
        logic="ICESTORM_LC", ram="ICESTORM_RAM", logic_name="LCs"),
    "ECP5 25F": dict(
        synth="synth_ecp5", pnr=["nextpnr-ecp5", "--25k", "--package", "CABGA256",
                                 "--lpf-allow-unconstrained"],
        logic="TRELLIS_COMB", ram="DP16KD", logic_name="LUT4s"),
}


def run(cmd):
    subprocess.run(cmd, cwd=HERE, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)


def implement(family, cfg, top):
    tag = f"{top}.{cfg['synth'].split('_')[1]}"
    js, rpt = f"build/{tag}.json", f"build/{tag}.report.json"
    stat = f"build/{tag}.stat"
    run(["yosys", "-q", "-l", f"build/{tag}.yosys.log", "-p",
         f"read_verilog -sv {' '.join(RTL)}; {cfg['synth']} -top {top} -json {js}; "
         f"tee -q -o {stat} stat"])
    run(cfg["pnr"] + ["--json", js, "--freq", str(TARGET_MHZ), "--seed", "1",
                      "--report", rpt, "-l", f"build/{tag}.pnr.log", "--quiet"])
    with open(os.path.join(HERE, rpt)) as f:
        r = json.load(f)
    util = r["utilization"]
    ff = 0
    with open(os.path.join(HERE, stat)) as f:          # final, flattened netlist
        for line in f:
            p = line.split()
            if len(p) == 2 and p[0].isdigit() and ("DFF" in p[1] or p[1] == "TRELLIS_FF"):
                ff += int(p[0])
    fmax = min(v["achieved"] for v in r["fmax"].values())
    return dict(family=family, top=top, logic=util[cfg["logic"]]["used"],
                logic_avail=util[cfg["logic"]]["available"], logic_name=cfg["logic_name"],
                ram=util.get(cfg["ram"], {}).get("used", 0), ff=ff, fmax=fmax)


def main():
    os.makedirs(BUILD, exist_ok=True)
    rows = [implement(fam, cfg, top) for fam, cfg in FAMILIES.items() for top in TOPS]
    lines = [
        "# FPGA implementation report",
        "",
        "Generated by `synth/run_synth.py` (Yosys + nextpnr, open-source flow). "
        f"Default parameters (DATA_WIDTH=8, DIV_WIDTH=16, FIFO_DEPTH=8, NUM_CS=4); "
        f"{TARGET_MHZ} MHz target; IOs unconstrained.",
        "",
        "| Device | Top | Logic | Flip-flops | Block RAM | Fmax | "
        f"{TARGET_MHZ} MHz |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        ok = "PASS" if r["fmax"] >= TARGET_MHZ else "FAIL"
        lines.append(f"| {r['family']} | `{r['top']}` | {r['logic']} {r['logic_name']} "
                     f"({100 * r['logic'] / r['logic_avail']:.1f}%) | {r['ff']} | {r['ram']} | "
                     f"{r['fmax']:.1f} MHz | {ok} |")
    report = "\n".join(lines) + "\n"
    with open(os.path.join(ROOT, "docs", "synth_report.md"), "w") as f:
        f.write(report)
    print(report)
    if "--check" in sys.argv and any(r["fmax"] < TARGET_MHZ for r in rows):
        sys.exit(1)


if __name__ == "__main__":
    main()
